// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/generator.proto

package generatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_generator_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_proto_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_generator_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_proto_generator_proto protoreflect.FileDescriptor

const file_proto_generator_proto_rawDesc = "" +
	"\n" +
	"\x15proto/generator.proto\x12\tgenerator\")\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\"&\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug2W\n" +
	"\x10GeneratorService\x12C\n" +
	"\bGenerate\x12\x1a.generator.GenerateRequest\x1a\x1b.generator.GenerateResponseB\x13Z\x11proto/generatorpbb\x06proto3"

var (
	file_proto_generator_proto_rawDescOnce sync.Once
	file_proto_generator_proto_rawDescData []byte
)

func file_proto_generator_proto_rawDescGZIP() []byte {
	file_proto_generator_proto_rawDescOnce.Do(func() {
		file_proto_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_generator_proto_rawDesc), len(file_proto_generator_proto_rawDesc)))
	})
	return file_proto_generator_proto_rawDescData
}

var file_proto_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_generator_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: generator.GenerateRequest
	(*GenerateResponse)(nil), // 1: generator.GenerateResponse
}
var file_proto_generator_proto_depIdxs = []int32{
	0, // 0: generator.GeneratorService.Generate:input_type -> generator.GenerateRequest
	1, // 1: generator.GeneratorService.Generate:output_type -> generator.GenerateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_generator_proto_init() }
func file_proto_generator_proto_init() {
	if File_proto_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_generator_proto_rawDesc), len(file_proto_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_generator_proto_goTypes,
		DependencyIndexes: file_proto_generator_proto_depIdxs,
		MessageInfos:      file_proto_generator_proto_msgTypes,
	}.Build()
	File_proto_generator_proto = out.File
	file_proto_generator_proto_goTypes = nil
	file_proto_generator_proto_depIdxs = nil
}
