apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decoder
  template:
    metadata:
      labels:
        app: decoder
    spec:
      containers:
        - name: decoder
          image: vault-decoder:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${DECODER_PORT}
