apiVersion: v1
kind: Service
metadata:
  name: decoder
spec:
  type: NodePort
  selector:
    app: decoder
  ports:
    - port: ${DECODER_PORT}
      targetPort: ${DECODER_PORT}
      nodePort: 30081
