apiVersion: v1
kind: Service
metadata:
  name: encoder
spec:
  type: NodePort
  selector:
    app: encoder
  ports:
    - port: ${ENCODER_PORT}
      targetPort: ${ENCODER_PORT}
      nodePort: 30080
