apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - name: generator
          image: vault-generator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${GENERATOR_PORT}
