apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: atennop/secure-vault:storage
          imagePullPolicy: Always
          ports:
            - containerPort: ${STORAGE_PORT}
